version: "3.8"
x-environment: &environment
  POSTGRES_USER: docker
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: postgres
  TZ: 'Asia/Tokyo'
services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: rust-db-libs-samples-app
    working_dir: /app
    command: bash
    tty: true
    environment:
      <<: *environment
      DATABASE_URL: "postgres://docker:password@postgres:5432/postgres"
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - rust-db-libs-samples-network
  postgres:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
      target: 'postgres'
    container_name: rust-db-libs-samples-postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment: *environment
    networks:
      - rust-db-libs-samples-network
networks:
  rust-db-libs-samples-network:
    driver: bridge
